Repository elwayman02/ember-sinon-qunit, pull requests merged in 2023-01, with the labels that each got.

#719 Ember Upgrade via blueprint
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .template-lintrc.js
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  config/environment.js
  config/release.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  vendor/.gitkeep
  yarn.lock
Labels: dependencies, internal

#727 Use ember-auto-import instead of ember-sinon
  README.md
  index.js
  package.json
  yarn.lock
Labels: enhancement, breaking

#729 Generate full changelog
  CHANGELOG.md
Labels: internal, documentation
