Repository elwayman02/ember-sinon-qunit, pull requests merged in 2023-10, with the labels that each got.

#893 Add ember-source 5 support
  .github/workflows/ci.yml
  README.md
  package.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: enhancement, dependencies

#906 Use Node 18 in CI
  package.json
Labels: internal

#909 Expand sinon peerDep to 17
  addon/package.json
  test-app/package.json
  yarn.lock
Labels: enhancement

#915 Update release-it setup to account for workspaces
  package.json
  test-app/package.json
  yarn.lock
Labels: internal

#916 Update Build Status badge inREADME
  README.md
Labels: documentation
